### ISSUE TITLE
Installer config file

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity-os-marketplace/.ubiquity-os#4]
1. The installer is fetching from all repos not just plugins (`.github`, this repo, etc) and we can ignore them by parsing a config file in here via a simple `opt.in/.out` like we have with plugins etc.
2. It's needed for https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/22 for a clean and optimal solution for template storage.
3. It will likely gather more uses for it as we iterate on the installer UI.

**Comment by Keyrxng** [comment]
@gentlementlegen @rndquu @zugdev Do you think we should do something like this?

**Comment by gentlementlegen** [comment]
I think it's a bit redundant. What are your trying to achieve exactly?

**Comment by zugdev** [comment]
I don't see a github option in plugin selection, what is the problem?

**Comment by Keyrxng** [comment]
> @Keyrxng I think we can simply:
> 
> 1. Fetch all repos from https://github.com/ubiquity-os-marketplace
> 2. If `manifest.json` exists in the root folder then it's a plugin, display it in https://github.com/ubiquity-os/ubiquity-os-plugin-installer

That solves for the slight annoyance of failed network requests, ideal.

My main point, which I could have put forward in a clearer way is: We need a place to store template configurations. Right now I've hardcoded three for the `minimal` template - https://github.com/ubiquity-os/ubiquity-os-plugin-installer/pull/28/files#diff-94071e7d80606fcfa081aaae82076f9468b056f9b078cb33cc80f1c0560c3c74.


So the cleaner and most optimal solution for templates would be an installer config file/folder that the installer fetches from


E.g:
```yml
ignoreRepos: [xyz,abc]
templates: {
 minimal: `yml config for this template`
 med: `yml config for this template`
 ...rest: ....
```
OR
`thisRepo/.github/installer/templates/minimal.yml`
`thisRepo/.github/installer/settings` >> `ignoreRepos` etc...

**Comment by Keyrxng** [comment]
> I don't see a github option in plugin selection, what is the problem?

Relevant PR: https://github.com/ubiquity-os/ubiquity-os-plugin-installer/pull/28
Relevant Task: https://github.com/ubiquity-os/ubiquity-os-plugin-installer/issues/22


![image](https://github.com/user-attachments/assets/4c988c0a-c706-47f8-bab1-8c8e1cbeff34)
